blank_issues_enabled: true
contact_links:
    - name: General Question
      url: https://github.com/sanshao85/tideterm/discussions
      about: Have a question on something? Start a new discussion thread.
    - name: Review open issues
      url: https://github.com/sanshao85/tideterm/issues
      about: Please check if your issue isn't already there.
